trigger:
  branches:
    include:
      - master

variables:
- group: TerraformSecrets   # ✅ securely defined in DevOps UI

pool:
  name: macOS-Agent-Pool

stages:
- stage: terraform
  jobs:
    - job: runTerraform
      steps:
        - checkout: self

        - script: terraform init
          displayName: Terraform Init

        - script: terraform validate
          displayName: Terraform Validate

        - script: terraform plan -out=tfplan
          displayName: Terraform Plan

        - script: terraform apply -auto-approve tfplan
          displayName: Terraform Apply
          env:
            ARM_CLIENT_ID: $(ARM_CLIENT_ID)
            ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
            ARM_TENANT_ID: $(ARM_TENANT_ID)
            ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
            TF_VAR_admin_password: $(TF_VAR_admin_password)
